# Generated by Django 5.2.17 on 2026-09-27 09:58

import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='rejoin_token',
            field=models.CharField(default=exams.models.make_rejoin_token, editable=False, max_length=32, unique=True),
        ),
    ]
