# Generated by Django 5.2.17 on 2026-09-27 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_attempt_rejoin_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
